[build]
command = "npm run build"
publish = ".next"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "18.18.0"

# Next.js routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200